# Sopwith Barnstormer -- build.
#
# Dependencies are deliberately minimal: libwayland-client and libxkbcommon,
# both of which any Wayland desktop already has.  ALSA is used for sound if
# it is present at build time and silently skipped if it is not.  Protocol
# glue is generated by wayland-scanner from the XML vendored in protocol/.

VERSION  := 1.1.0

PKG      ?= pkg-config
CC       ?= cc
PREFIX   ?= /usr/local
BINDIR   ?= $(PREFIX)/bin

BUILD    := build
BIN      := $(BUILD)/barnstormer

WARN     := -Wall -Wextra -Wshadow -Wstrict-prototypes -Wno-unused-parameter
CFLAGS   ?= -O2 -g
CFLAGS   += -std=c11 $(WARN) -Iinclude -I$(BUILD)/protocol
CFLAGS   += -DBARNSTORMER_VERSION=\"$(VERSION)\"
LDFLAGS  ?=
LDLIBS   := -lm

WL_CFLAGS := $(shell $(PKG) --cflags wayland-client xkbcommon)
WL_LIBS   := $(shell $(PKG) --libs   wayland-client xkbcommon)
CFLAGS    += $(WL_CFLAGS)
LDLIBS    += $(WL_LIBS)

HAVE_ALSA := $(shell $(PKG) --exists alsa && echo 1)
ifeq ($(HAVE_ALSA),1)
CFLAGS += -DHAVE_ALSA $(shell $(PKG) --cflags alsa)
LDLIBS += $(shell $(PKG) --libs alsa)
endif

SCANNER  := wayland-scanner
PROTOS   := protocol/xdg-shell.xml \
            protocol/wlr-layer-shell-unstable-v1.xml \
            protocol/viewporter.xml \
            protocol/fractional-scale-v1.xml
PROTO_H  := $(patsubst protocol/%.xml,$(BUILD)/protocol/%-client-protocol.h,$(PROTOS))
PROTO_C  := $(patsubst protocol/%.xml,$(BUILD)/protocol/%-protocol.c,$(PROTOS))

SRC := main.c \
       game/game.c game/move.c game/collision.c game/autopilot.c \
       game/objects.c game/sound.c game/level.c game/net.c game/score.c \
       data/sprites.c data/level_classic.c \
       render/raster.c render/scene.c render/font.c render/sprites_solid.c \
       platform/wl_backend.c \
       audio/audio.c

OBJ := $(patsubst %.c,$(BUILD)/%.o,$(SRC)) \
       $(patsubst $(BUILD)/protocol/%.c,$(BUILD)/protocol/%.o,$(PROTO_C))

# Keep the generated protocol sources around: make would otherwise treat
# them as intermediates and delete them, which makes debug builds awkward.
.PRECIOUS: $(PROTO_C) $(PROTO_H)

.PHONY: all clean run run-breakout install regen-data
all: $(BIN)

$(BIN): $(OBJ)
	@mkdir -p $(dir $@)
	$(CC) $(LDFLAGS) -o $@ $(OBJ) $(LDLIBS)

# Every object depends on the generated protocol headers.
$(OBJ): | $(PROTO_H)

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

$(BUILD)/protocol/%.o: $(BUILD)/protocol/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -w -c $< -o $@

$(BUILD)/protocol/%-client-protocol.h: protocol/%.xml
	@mkdir -p $(dir $@)
	$(SCANNER) client-header $< $@

$(BUILD)/protocol/%-protocol.c: protocol/%.xml
	@mkdir -p $(dir $@)
	$(SCANNER) private-code $< $@

# Re-derive the artwork and terrain from the original sources in ../origsrc.
regen-data:
	python3 tools/extract_sprites.py ../origsrc data/sprites.c \
	        include/sprites_gen.h
	python3 tools/extract_world.py ../origsrc data/level_classic.c
	python3 tools/make_icon.py ../origsrc barnstormer.svg
	python3 tools/make_icon.py ../origsrc barnstormer-overlay.svg enemy

run: $(BIN)
	$(BIN)

run-breakout: $(BIN)
	$(BIN) --breakout

install: $(BIN)
	install -Dm755 $(BIN) $(DESTDIR)$(BINDIR)/barnstormer
	install -Dm644 barnstormer.desktop \
	    $(DESTDIR)$(PREFIX)/share/applications/barnstormer.desktop
	install -Dm644 barnstormer-overlay.desktop \
	    $(DESTDIR)$(PREFIX)/share/applications/barnstormer-overlay.desktop
	install -Dm644 barnstormer.svg \
	    $(DESTDIR)$(PREFIX)/share/icons/hicolor/scalable/apps/barnstormer.svg
	install -Dm644 barnstormer-overlay.svg \
	    $(DESTDIR)$(PREFIX)/share/icons/hicolor/scalable/apps/barnstormer-overlay.svg
	install -Dm644 LICENSE \
	    $(DESTDIR)$(PREFIX)/share/licenses/barnstormer/LICENSE
	install -Dm644 LICENSE.origsopwith.txt \
	    $(DESTDIR)$(PREFIX)/share/licenses/barnstormer/LICENSE.origsopwith.txt

clean:
	rm -rf $(BUILD)

-include $(shell find $(BUILD) -name '*.d' 2>/dev/null)

# ---- headless simulation test ----------------------------------------------
TEST_SRC := tests/simtest.c \
            game/game.c game/move.c game/collision.c game/autopilot.c \
            game/objects.c game/sound.c game/level.c game/net.c \
            data/sprites.c data/level_classic.c
TEST_BIN := $(BUILD)/simtest

SCORE_TEST_SRC := tests/scoretest.c game/score.c
SCORE_TEST_BIN := $(BUILD)/scoretest

.PHONY: test
test: $(TEST_BIN) $(SCORE_TEST_BIN)
	$(TEST_BIN)
	@echo
	$(SCORE_TEST_BIN)

$(TEST_BIN): $(TEST_SRC) | $(PROTO_H)
	@mkdir -p $(dir $@)
	$(CC) -std=c11 $(WARN) -Iinclude -O1 -g -fsanitize=address,undefined \
	    -o $@ $(TEST_SRC) -lm

# Drives the real binary through every screen with synthetic key events, so
# it needs a compositor and takes the keyboard for a few seconds.  Kept out of
# `test` for that reason.
.PHONY: test-ui
test-ui: $(BIN)
	BIN=$(BIN) tests/uiflow.sh

$(SCORE_TEST_BIN): $(SCORE_TEST_SRC)
	@mkdir -p $(dir $@)
	$(CC) -std=c11 $(WARN) -Iinclude -O1 -g -fsanitize=address,undefined \
	    -o $@ $(SCORE_TEST_SRC)
