/* Generated by tools/extract_sprites.py -- do not edit.
 * Bitmaps derived from the original Sopwith sources,
 * Copyright (C) 1984-2000 David L. Clark.
 * See LICENSE.origsopwith.txt.
 */
#ifndef SPRITES_GEN_H
#define SPRITES_GEN_H

enum {
    SPRITE_PLANE,        /* 32 frames, 16x16 */
    SPRITE_PLANE_HIT,    /*  2 frames, 16x16 */
    SPRITE_WINNER,       /*  4 frames, 16x16 */
    SPRITE_BOMB,         /*  8 frames,  8x8  */
    SPRITE_MISSILE,      /* 16 frames,  8x8  */
    SPRITE_STARBURST,    /*  2 frames,  8x8  */
    SPRITE_EXPLOSION,    /*  8 frames,  8x8  */
    SPRITE_TARGET,       /*  4 frames, 16x16 */
    SPRITE_TARGET_HIT,   /*  1 frames, 16x16 */
    SPRITE_FLOCK,        /*  2 frames, 16x16 */
    SPRITE_BIRD,         /*  2 frames,  4x2  */
    SPRITE_OX,           /*  2 frames, 16x16 */
    SPRITE_GHOST,        /*  1 frames,  8x8  */
    SPRITE_SHOTHOLE,     /*  1 frames, 16x16 */
    SPRITE_SPLAT,        /*  1 frames, 32x32 */
    SPRITE_SET_COUNT
};

#endif
