#!/usr/bin/env python3
"""Extract the stock terrain and level layout from the original sources.

Reads origsrc/SWGROUND.C (the 3000-entry height field) and origsrc/SWGAMES.C
(runway positions/orientations and the twenty building sites), plus the ox and
flock spawn tables that SWINIT.C hard-codes, and emits src/data/level_classic.c.

    python3 src/tools/extract_world.py origsrc src/data/level_classic.c
"""

import re
import sys
import os


def nums(text):
    return [int(v) for v in re.findall(r"-?\d+", text)]


def strip_comments(text):
    return re.sub(r"/\*.*?\*/", " ", text, flags=re.S)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "origsrc"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/data/level_classic.c"

    ground_src = open(os.path.join(src, "SWGROUND.C"), errors="replace").read()
    body = ground_src.split("orground[MAX_X] = {", 1)[1].split("};", 1)[0]
    ground = nums(strip_comments(body))
    assert len(ground) == 3000, len(ground)

    games_src = strip_comments(open(os.path.join(src, "SWGAMES.C"), errors="replace").read())
    body = games_src.split("swgames[1] = {", 1)[1]
    # gm_x[8], gm_orient[8], NULL, seed, NULL, gm_xtarg[20], gm_ttarg[20]
    vals = re.findall(r"NULL|-?\d+", body)
    runway_x = [int(v) for v in vals[0:8]]
    runway_o = [int(v) for v in vals[8:16]]
    assert vals[16] == "NULL" and vals[18] == "NULL", vals[16:19]
    seed = int(vals[17])
    targ_x = [int(v) for v in vals[19:39]]
    targ_t = [int(v) for v in vals[39:59]]

    # SWINIT.C: initoxen()'s iox[]/ioy[] and initflck()'s ifx[]/ify[]/ifdx[]
    init_src = strip_comments(open(os.path.join(src, "SWINIT.C"), errors="replace").read())
    iox = nums(init_src.split("iox[] = {", 1)[1].split("}", 1)[0])
    ioy = nums(init_src.split("ioy[] = {", 1)[1].split("}", 1)[0])

    with open(dst, "w") as f:
        f.write("/* Generated by tools/extract_world.py -- do not edit.\n"
                " * Terrain and layout transcribed from the original Sopwith sources,\n"
                " * Copyright (C) 1984-2000 David L. Clark.\n"
                " * See LICENSE.origsopwith.txt.\n"
                " */\n#include \"level.h\"\n\n")

        f.write("static const uint8_t classic_ground[MAX_X] = {\n")
        for i in range(0, len(ground), 20):
            f.write("    " + ",".join("%3d" % g for g in ground[i:i + 20]) + ",\n")
        f.write("};\n\n")

        f.write("/* Eight runway slots.  Which of them are used, and by whom,\n"
                " * depends on the play mode; see level_runway_slot().          */\n")
        f.write("static const level_runway_t classic_runways[] = {\n")
        for x, o in zip(runway_x, runway_o):
            f.write("    { %4d, %d },\n" % (x, o))
        f.write("};\n\n")

        f.write("static const level_target_t classic_targets[] = {\n")
        for x, t in zip(targ_x, targ_t):
            f.write("    { %4d, %d },\n" % (x, t))
        f.write("};\n\n")

        f.write("static const level_point_t classic_oxen[] = {\n")
        for x, y in zip(iox, ioy):
            f.write("    { %4d, %3d },\n" % (x, y))
        f.write("};\n\n")

        f.write("const level_t level_classic = {\n")
        f.write('    .name       = "Classic",\n')
        f.write("    .format     = LEVEL_FORMAT_VERSION,\n")
        f.write("    .width      = MAX_X,\n")
        f.write("    .height     = MAX_Y,\n")
        f.write("    .rand_seed  = %d,\n" % seed)
        f.write("    .ground     = classic_ground,\n")
        f.write("    .runways    = classic_runways,\n")
        f.write("    .n_runways  = %d,\n" % len(runway_x))
        f.write("    .targets    = classic_targets,\n")
        f.write("    .n_targets  = %d,\n" % len(targ_x))
        f.write("    .oxen       = classic_oxen,\n")
        f.write("    .n_oxen     = %d,\n" % len(iox))
        f.write("};\n")
    print("wrote %s" % dst)


if __name__ == "__main__":
    main()
