#!/usr/bin/env python3
"""Extract CGA 2bpp sprite bitmaps from the original Sopwith C sources.

The original sources (origsrc/SWPLANES.C, origsrc/SWSYMBOL.C) store every
symbol as a packed CGA bitmap: 2 bits per pixel, most-significant bits first,
rows top to bottom, (width*height)/4 bytes per symbol.  Colour 0 is
transparent; colours 1..3 index the CGA palette.

This script re-emits that data as a flat, one-byte-per-pixel C array so the
renderer never has to unpack bit fields at run time.  Run it from the repo
root:  python3 src/tools/extract_sprites.py origsrc src/data/sprites.c
"""

import re
import sys
import os

# original array name -> (enum name, width, height).  Dimensions come from
# SW.H's *BYTES macros and the ob_symwdt/ob_symhgt fields set in SWINIT.C.
# The order here is the order of the generated enum.
SYMBOLS = [
    ("swplnsym", "SPRITE_PLANE",      16, 16),
    ("swhitsym", "SPRITE_PLANE_HIT",  16, 16),
    ("swwinsym", "SPRITE_WINNER",     16, 16),
    ("swbmbsym", "SPRITE_BOMB",        8,  8),
    ("swmscsym", "SPRITE_MISSILE",     8,  8),
    ("swbstsym", "SPRITE_STARBURST",   8,  8),
    ("swexpsym", "SPRITE_EXPLOSION",   8,  8),
    ("swtrgsym", "SPRITE_TARGET",     16, 16),
    ("swhtrsym", "SPRITE_TARGET_HIT", 16, 16),
    ("swflksym", "SPRITE_FLOCK",      16, 16),
    ("swbrdsym", "SPRITE_BIRD",        4,  2),
    ("swoxsym",  "SPRITE_OX",         16, 16),
    ("swghtsym", "SPRITE_GHOST",       8,  8),
    ("swshtsym", "SPRITE_SHOTHOLE",   16, 16),
    ("swsplsym", "SPRITE_SPLAT",      32, 32),
]

GEOM = {n: (w, h) for n, _, w, h in SYMBOLS}
ENUM = {n: e for n, e, _, _ in SYMBOLS}


def strip_comments(text):
    return re.sub(r"/\*.*?\*/", " ", text, flags=re.S)


def parse_arrays(text):
    """Yield (name, [byte, ...]) for every `char name[...] = { ... };`."""
    text = strip_comments(text)
    for m in re.finditer(r"char\s+(\w+)\s*((?:\[[^\]]*\]\s*)+)=\s*\{", text):
        name = m.group(1)
        if name not in GEOM:
            continue
        depth = 1
        i = m.end()
        while depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[m.end():i - 1]
        vals = [int(v, 0) & 0xFF for v in re.findall(r"0[xX][0-9a-fA-F]+|\d+", body)]
        yield name, vals


def unpack(vals, w, h):
    """Split a flat byte list into a list of w*h colour-index buffers."""
    per = w * h // 4
    if len(vals) % per:
        raise SystemExit("size mismatch: %d bytes, %d per symbol" % (len(vals), per))
    out = []
    for base in range(0, len(vals), per):
        px = bytearray(w * h)
        for row in range(h):
            for byte in range(w // 4):
                b = vals[base + row * (w // 4) + byte]
                for k in range(4):
                    px[row * w + byte * 4 + k] = (b >> (6 - 2 * k)) & 3
        out.append(px)
    return out


def preview(px, w, h):
    chars = " .oO"
    return "\n".join("".join(chars[px[y * w + x]] for x in range(w)) for y in range(h))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "origsrc"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/data/sprites.c"
    hdr = sys.argv[3] if len(sys.argv) > 3 else "src/include/sprites_gen.h"

    sets = {}
    for fn in ("SWPLANES.C", "SWSYMBOL.C"):
        with open(os.path.join(src, fn), "r", errors="replace") as f:
            for name, vals in parse_arrays(f.read()):
                w, h = GEOM[name]
                sets[name] = (w, h, unpack(vals, w, h))

    if "--preview" in sys.argv:
        for name, _, _, _ in SYMBOLS:
            w, h, frames = sets[name]
            for i, px in enumerate(frames):
                print("== %s[%d] %dx%d" % (name, i, w, h))
                print(preview(px, w, h))
        return

    banner = ("/* Generated by tools/extract_sprites.py -- do not edit.\n"
              " * Bitmaps derived from the original Sopwith sources,\n"
              " * Copyright (C) 1984-2000 David L. Clark.\n"
              " * See LICENSE.origsopwith.txt.\n"
              " */\n")

    with open(hdr, "w") as f:
        f.write(banner)
        f.write("#ifndef SPRITES_GEN_H\n#define SPRITES_GEN_H\n\nenum {\n")
        for name, enum, _, _ in SYMBOLS:
            w, h, frames = sets[name]
            f.write("    %-20s /* %2d frames, %2dx%-2d */\n"
                    % (enum + ",", len(frames), w, h))
        f.write("    SPRITE_SET_COUNT\n};\n\n#endif\n")

    with open(dst, "w") as f:
        f.write(banner)
        f.write('#include "sprites.h"\n\n')
        for name, enum, _, _ in SYMBOLS:
            w, h, frames = sets[name]
            f.write("static const uint8_t %s_px[] = {\n" % name)
            for px in frames:
                for y in range(h):
                    f.write("    " + ",".join(str(px[y * w + x]) for x in range(w)) + ",\n")
                f.write("\n")
            f.write("};\n\n")
        f.write("const sprite_set_t sw_sprite_sets[SPRITE_SET_COUNT] = {\n")
        for name, enum, _, _ in SYMBOLS:
            w, h, frames = sets[name]
            f.write('    [%s] = { "%s", %d, %d, %d, %s_px },\n'
                    % (enum, name, w, h, len(frames), name))
        f.write("};\n")
    print("wrote %s and %s (%d sets)" % (dst, hdr, len(sets)))


if __name__ == "__main__":
    main()
