#!/bin/bash
#
# mkpkgbuild.sh -- generate the distribution PKGBUILD for a published tag.
#
#     tools/mkpkgbuild.sh            # version from the Makefile
#     tools/mkpkgbuild.sh 1.0.2
#
# Writes dist/PKGBUILD and dist/.SRCINFO with a real sha256 of the tag
# tarball, for attaching to the release and for the AUR.
#
# The tag must already be pushed: its tarball is what gets hashed. The script
# refuses to emit a PKGBUILD whose checksum is SKIP or otherwise unset, so a
# release cannot go out with integrity checking silently disabled.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

VERSION="${1:-$(sed -n 's/^VERSION[[:space:]]*:=[[:space:]]*//p' Makefile)}"
[[ -n $VERSION ]] || { echo "cannot determine version" >&2; exit 1; }

PKGNAME=barnstormer
URL="https://github.com/choyer/barnstormer"
TAG="v$VERSION"
TARBALL_URL="$URL/archive/refs/tags/$TAG.tar.gz"
OUT=dist

say() { printf '  %s\n' "$*" >&2; }

echo "generating PKGBUILD for $TAG" >&2

# The tag has to exist, or we would be hashing a 404 page.
git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1 || {
  echo "error: tag $TAG is not on origin -- push it first" >&2
  echo "       git tag -a $TAG -m \"Barnstormer $VERSION\" && git push origin $TAG" >&2
  exit 1
}
say "tag $TAG is on origin"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# GitHub's generated archives have not always been byte-stable. A checksum
# that drifts breaks the package for everyone downstream, so fetch twice and
# insist the two agree before pinning one.
curl -fsSL -o "$tmp/a.tar.gz" "$TARBALL_URL"
curl -fsSL -o "$tmp/b.tar.gz" "$TARBALL_URL"
SUM=$(sha256sum "$tmp/a.tar.gz" | cut -d' ' -f1)
SUM2=$(sha256sum "$tmp/b.tar.gz" | cut -d' ' -f1)
[[ $SUM == "$SUM2" ]] || {
  echo "error: the tag tarball hashed differently on two fetches:" >&2
  echo "       $SUM" >&2
  echo "       $SUM2" >&2
  echo "       refusing to pin an unstable checksum" >&2
  exit 1
}
say "tarball hashes the same twice: ${SUM:0:16}..."

# The tarball must actually be the version it claims, or the checksum is
# right and the package is still wrong.
INNER=$(tar xzOf "$tmp/a.tar.gz" "$PKGNAME-$VERSION/Makefile" 2>/dev/null |
        sed -n 's/^VERSION[[:space:]]*:=[[:space:]]*//p')
[[ $INNER == "$VERSION" ]] || {
  echo "error: $TAG contains VERSION '$INNER', expected '$VERSION'" >&2
  exit 1
}
say "tag contents report version $INNER"

mkdir -p "$OUT"
cat > "$OUT/PKGBUILD" <<EOF
# Maintainer: Carl Hoyer <carl@hoyer.ca>
#
# Generated by tools/mkpkgbuild.sh for $TAG -- do not edit by hand.
# To build from a checkout instead, use packaging/PKGBUILD.

pkgname=$PKGNAME
pkgver=$VERSION
pkgrel=1
pkgdesc="Sopwith re-implemented for Wayland: a 1984 biplane dogfight in a window or as a desktop overlay"
arch=('x86_64')
url="$URL"
license=('GPL-3.0-or-later')
depends=('wayland' 'libxkbcommon' 'alsa-lib')
makedepends=('wayland')   # wayland-scanner
source=("\$pkgname-\$pkgver.tar.gz::\$url/archive/refs/tags/v\$pkgver.tar.gz")
sha256sums=('$SUM')

build() {
  cd "\$pkgname-\$pkgver"
  make
}

check() {
  cd "\$pkgname-\$pkgver"
  make test
}

package() {
  cd "\$pkgname-\$pkgver"
  make install PREFIX=/usr DESTDIR="\$pkgdir"
}
EOF

# The whole point of this script: never ship an unverified source.
if grep -qE "sha256sums=\(.*(SKIP|''|\"\").*\)" "$OUT/PKGBUILD"; then
  echo "error: generated PKGBUILD has no real checksum -- refusing to write" >&2
  rm -f "$OUT/PKGBUILD"
  exit 1
fi

if command -v makepkg >/dev/null; then
  (cd "$OUT" && makepkg --printsrcinfo > .SRCINFO)
  say "wrote $OUT/.SRCINFO"
else
  say "makepkg not found; .SRCINFO not generated (run on Arch to produce it)"
fi

echo >&2
echo "$OUT/PKGBUILD  sha256sums=('$SUM')" >&2
echo >&2
echo "verify and attach:" >&2
echo "  (cd $OUT && makepkg --verifysource)" >&2
echo "  gh release upload $TAG $OUT/PKGBUILD $OUT/.SRCINFO" >&2
